version: 2

project_name: vex

before:
  hooks:
    - go mod tidy

builds:
  - id: vex
    main: ./cmd/vex
    binary: vex
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/vexsearch/vex/cmd/vex/version.Version={{.Version}}
      - -X github.com/vexsearch/vex/cmd/vex/version.GitCommit={{.Commit}}
      - -X github.com/vexsearch/vex/cmd/vex/version.BuildTime={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - SPEC.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
