// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: internal/wal/entry.proto

package wal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutationType int32

const (
	MutationType_MUTATION_TYPE_UNSPECIFIED MutationType = 0
	MutationType_MUTATION_TYPE_UPSERT      MutationType = 1
	MutationType_MUTATION_TYPE_PATCH       MutationType = 2
	MutationType_MUTATION_TYPE_DELETE      MutationType = 3
)

// Enum value maps for MutationType.
var (
	MutationType_name = map[int32]string{
		0: "MUTATION_TYPE_UNSPECIFIED",
		1: "MUTATION_TYPE_UPSERT",
		2: "MUTATION_TYPE_PATCH",
		3: "MUTATION_TYPE_DELETE",
	}
	MutationType_value = map[string]int32{
		"MUTATION_TYPE_UNSPECIFIED": 0,
		"MUTATION_TYPE_UPSERT":      1,
		"MUTATION_TYPE_PATCH":       2,
		"MUTATION_TYPE_DELETE":      3,
	}
)

func (x MutationType) Enum() *MutationType {
	p := new(MutationType)
	*p = x
	return p
}

func (x MutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_wal_entry_proto_enumTypes[0].Descriptor()
}

func (MutationType) Type() protoreflect.EnumType {
	return &file_internal_wal_entry_proto_enumTypes[0]
}

func (x MutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationType.Descriptor instead.
func (MutationType) EnumDescriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{0}
}

type AttributeType int32

const (
	AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED    AttributeType = 0
	AttributeType_ATTRIBUTE_TYPE_STRING         AttributeType = 1
	AttributeType_ATTRIBUTE_TYPE_INT            AttributeType = 2
	AttributeType_ATTRIBUTE_TYPE_UINT           AttributeType = 3
	AttributeType_ATTRIBUTE_TYPE_FLOAT          AttributeType = 4
	AttributeType_ATTRIBUTE_TYPE_UUID           AttributeType = 5
	AttributeType_ATTRIBUTE_TYPE_DATETIME       AttributeType = 6
	AttributeType_ATTRIBUTE_TYPE_BOOL           AttributeType = 7
	AttributeType_ATTRIBUTE_TYPE_STRING_ARRAY   AttributeType = 11
	AttributeType_ATTRIBUTE_TYPE_INT_ARRAY      AttributeType = 12
	AttributeType_ATTRIBUTE_TYPE_UINT_ARRAY     AttributeType = 13
	AttributeType_ATTRIBUTE_TYPE_FLOAT_ARRAY    AttributeType = 14
	AttributeType_ATTRIBUTE_TYPE_UUID_ARRAY     AttributeType = 15
	AttributeType_ATTRIBUTE_TYPE_DATETIME_ARRAY AttributeType = 16
	AttributeType_ATTRIBUTE_TYPE_BOOL_ARRAY     AttributeType = 17
)

// Enum value maps for AttributeType.
var (
	AttributeType_name = map[int32]string{
		0:  "ATTRIBUTE_TYPE_UNSPECIFIED",
		1:  "ATTRIBUTE_TYPE_STRING",
		2:  "ATTRIBUTE_TYPE_INT",
		3:  "ATTRIBUTE_TYPE_UINT",
		4:  "ATTRIBUTE_TYPE_FLOAT",
		5:  "ATTRIBUTE_TYPE_UUID",
		6:  "ATTRIBUTE_TYPE_DATETIME",
		7:  "ATTRIBUTE_TYPE_BOOL",
		11: "ATTRIBUTE_TYPE_STRING_ARRAY",
		12: "ATTRIBUTE_TYPE_INT_ARRAY",
		13: "ATTRIBUTE_TYPE_UINT_ARRAY",
		14: "ATTRIBUTE_TYPE_FLOAT_ARRAY",
		15: "ATTRIBUTE_TYPE_UUID_ARRAY",
		16: "ATTRIBUTE_TYPE_DATETIME_ARRAY",
		17: "ATTRIBUTE_TYPE_BOOL_ARRAY",
	}
	AttributeType_value = map[string]int32{
		"ATTRIBUTE_TYPE_UNSPECIFIED":    0,
		"ATTRIBUTE_TYPE_STRING":         1,
		"ATTRIBUTE_TYPE_INT":            2,
		"ATTRIBUTE_TYPE_UINT":           3,
		"ATTRIBUTE_TYPE_FLOAT":          4,
		"ATTRIBUTE_TYPE_UUID":           5,
		"ATTRIBUTE_TYPE_DATETIME":       6,
		"ATTRIBUTE_TYPE_BOOL":           7,
		"ATTRIBUTE_TYPE_STRING_ARRAY":   11,
		"ATTRIBUTE_TYPE_INT_ARRAY":      12,
		"ATTRIBUTE_TYPE_UINT_ARRAY":     13,
		"ATTRIBUTE_TYPE_FLOAT_ARRAY":    14,
		"ATTRIBUTE_TYPE_UUID_ARRAY":     15,
		"ATTRIBUTE_TYPE_DATETIME_ARRAY": 16,
		"ATTRIBUTE_TYPE_BOOL_ARRAY":     17,
	}
)

func (x AttributeType) Enum() *AttributeType {
	p := new(AttributeType)
	*p = x
	return p
}

func (x AttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_wal_entry_proto_enumTypes[1].Descriptor()
}

func (AttributeType) Type() protoreflect.EnumType {
	return &file_internal_wal_entry_proto_enumTypes[1]
}

func (x AttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeType.Descriptor instead.
func (AttributeType) EnumDescriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{1}
}

type FilterOperationType int32

const (
	FilterOperationType_FILTER_OPERATION_TYPE_UNSPECIFIED FilterOperationType = 0
	FilterOperationType_FILTER_OPERATION_TYPE_DELETE      FilterOperationType = 1
	FilterOperationType_FILTER_OPERATION_TYPE_PATCH       FilterOperationType = 2
)

// Enum value maps for FilterOperationType.
var (
	FilterOperationType_name = map[int32]string{
		0: "FILTER_OPERATION_TYPE_UNSPECIFIED",
		1: "FILTER_OPERATION_TYPE_DELETE",
		2: "FILTER_OPERATION_TYPE_PATCH",
	}
	FilterOperationType_value = map[string]int32{
		"FILTER_OPERATION_TYPE_UNSPECIFIED": 0,
		"FILTER_OPERATION_TYPE_DELETE":      1,
		"FILTER_OPERATION_TYPE_PATCH":       2,
	}
)

func (x FilterOperationType) Enum() *FilterOperationType {
	p := new(FilterOperationType)
	*p = x
	return p
}

func (x FilterOperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_wal_entry_proto_enumTypes[2].Descriptor()
}

func (FilterOperationType) Type() protoreflect.EnumType {
	return &file_internal_wal_entry_proto_enumTypes[2]
}

func (x FilterOperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperationType.Descriptor instead.
func (FilterOperationType) EnumDescriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{2}
}

// WalEntry is the top-level WAL record stored as a .wal.zst compressed blob.
// A single WAL entry may contain multiple sub-batches, one per HTTP write request.
type WalEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema format version (for forward compatibility)
	FormatVersion uint32 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// Namespace this WAL entry belongs to
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Monotonically increasing sequence number (strictly increases by 1)
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Unix timestamp in milliseconds when this entry was committed
	CommittedUnixMs int64 `protobuf:"varint,4,opt,name=committed_unix_ms,json=committedUnixMs,proto3" json:"committed_unix_ms,omitempty"`
	// Multiple sub-batches (one per HTTP request in the batch window)
	SubBatches []*WriteSubBatch `protobuf:"bytes,5,rep,name=sub_batches,json=subBatches,proto3" json:"sub_batches,omitempty"`
	// SHA-256 checksum of the uncompressed protobuf payload (before compression)
	Checksum      []byte `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalEntry) Reset() {
	*x = WalEntry{}
	mi := &file_internal_wal_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalEntry) ProtoMessage() {}

func (x *WalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalEntry.ProtoReflect.Descriptor instead.
func (*WalEntry) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{0}
}

func (x *WalEntry) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *WalEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WalEntry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WalEntry) GetCommittedUnixMs() int64 {
	if x != nil {
		return x.CommittedUnixMs
	}
	return 0
}

func (x *WalEntry) GetSubBatches() []*WriteSubBatch {
	if x != nil {
		return x.SubBatches
	}
	return nil
}

func (x *WalEntry) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// WriteSubBatch represents a single HTTP write request within a WAL entry.
// Each sub-batch is atomic and serialized (deterministic order).
type WriteSubBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request ID for idempotency and deduplication
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Unix timestamp in milliseconds when the request was received
	ReceivedAtMs int64 `protobuf:"varint,2,opt,name=received_at_ms,json=receivedAtMs,proto3" json:"received_at_ms,omitempty"`
	// Mutations to apply (upserts, patches, deletes)
	Mutations []*Mutation `protobuf:"bytes,3,rep,name=mutations,proto3" json:"mutations,omitempty"`
	// Statistics about the batch
	Stats *SubBatchStats `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	// Schema delta (new fields or type definitions added by this batch)
	SchemaDeltas []*SchemaDelta `protobuf:"bytes,5,rep,name=schema_deltas,json=schemaDeltas,proto3" json:"schema_deltas,omitempty"`
	// Filter-based operation details (if applicable)
	FilterOp      *FilterOperation `protobuf:"bytes,6,opt,name=filter_op,json=filterOp,proto3" json:"filter_op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSubBatch) Reset() {
	*x = WriteSubBatch{}
	mi := &file_internal_wal_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSubBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSubBatch) ProtoMessage() {}

func (x *WriteSubBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSubBatch.ProtoReflect.Descriptor instead.
func (*WriteSubBatch) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{1}
}

func (x *WriteSubBatch) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteSubBatch) GetReceivedAtMs() int64 {
	if x != nil {
		return x.ReceivedAtMs
	}
	return 0
}

func (x *WriteSubBatch) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *WriteSubBatch) GetStats() *SubBatchStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *WriteSubBatch) GetSchemaDeltas() []*SchemaDelta {
	if x != nil {
		return x.SchemaDeltas
	}
	return nil
}

func (x *WriteSubBatch) GetFilterOp() *FilterOperation {
	if x != nil {
		return x.FilterOp
	}
	return nil
}

// Mutation represents a single document mutation.
type Mutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of mutation
	Type MutationType `protobuf:"varint,1,opt,name=type,proto3,enum=wal.MutationType" json:"type,omitempty"`
	// Document ID
	Id *DocumentID `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Attributes to set/update (for upserts and patches)
	// Keys are sorted alphabetically for deterministic encoding
	Attributes map[string]*AttributeValue `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Vector data (if present)
	Vector []byte `protobuf:"bytes,4,opt,name=vector,proto3" json:"vector,omitempty"`
	// Vector dimensions (for validation)
	VectorDims uint32 `protobuf:"varint,5,opt,name=vector_dims,json=vectorDims,proto3" json:"vector_dims,omitempty"`
	// Whether this mutation was conditional and the condition result
	Conditional   bool `protobuf:"varint,6,opt,name=conditional,proto3" json:"conditional,omitempty"`
	ConditionMet  bool `protobuf:"varint,7,opt,name=condition_met,json=conditionMet,proto3" json:"condition_met,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_internal_wal_entry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{2}
}

func (x *Mutation) GetType() MutationType {
	if x != nil {
		return x.Type
	}
	return MutationType_MUTATION_TYPE_UNSPECIFIED
}

func (x *Mutation) GetId() *DocumentID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Mutation) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Mutation) GetVector() []byte {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Mutation) GetVectorDims() uint32 {
	if x != nil {
		return x.VectorDims
	}
	return 0
}

func (x *Mutation) GetConditional() bool {
	if x != nil {
		return x.Conditional
	}
	return false
}

func (x *Mutation) GetConditionMet() bool {
	if x != nil {
		return x.ConditionMet
	}
	return false
}

// DocumentID represents a normalized document ID.
type DocumentID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*DocumentID_U64
	//	*DocumentID_Uuid
	//	*DocumentID_Str
	Id            isDocumentID_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentID) Reset() {
	*x = DocumentID{}
	mi := &file_internal_wal_entry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentID) ProtoMessage() {}

func (x *DocumentID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentID.ProtoReflect.Descriptor instead.
func (*DocumentID) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentID) GetId() isDocumentID_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DocumentID) GetU64() uint64 {
	if x != nil {
		if x, ok := x.Id.(*DocumentID_U64); ok {
			return x.U64
		}
	}
	return 0
}

func (x *DocumentID) GetUuid() []byte {
	if x != nil {
		if x, ok := x.Id.(*DocumentID_Uuid); ok {
			return x.Uuid
		}
	}
	return nil
}

func (x *DocumentID) GetStr() string {
	if x != nil {
		if x, ok := x.Id.(*DocumentID_Str); ok {
			return x.Str
		}
	}
	return ""
}

type isDocumentID_Id interface {
	isDocumentID_Id()
}

type DocumentID_U64 struct {
	U64 uint64 `protobuf:"varint,1,opt,name=u64,proto3,oneof"`
}

type DocumentID_Uuid struct {
	Uuid []byte `protobuf:"bytes,2,opt,name=uuid,proto3,oneof"` // 16 bytes
}

type DocumentID_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"`
}

func (*DocumentID_U64) isDocumentID_Id() {}

func (*DocumentID_Uuid) isDocumentID_Id() {}

func (*DocumentID_Str) isDocumentID_Id() {}

// AttributeValue represents a typed attribute value.
type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AttributeValue_StringVal
	//	*AttributeValue_IntVal
	//	*AttributeValue_UintVal
	//	*AttributeValue_FloatVal
	//	*AttributeValue_UuidVal
	//	*AttributeValue_DatetimeVal
	//	*AttributeValue_BoolVal
	//	*AttributeValue_NullVal
	//	*AttributeValue_StringArray
	//	*AttributeValue_IntArray
	//	*AttributeValue_UintArray
	//	*AttributeValue_FloatArray
	//	*AttributeValue_UuidArray
	//	*AttributeValue_DatetimeArray
	//	*AttributeValue_BoolArray
	Value         isAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_internal_wal_entry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeValue) GetValue() isAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeValue) GetStringVal() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

func (x *AttributeValue) GetIntVal() int64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *AttributeValue) GetUintVal() uint64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_UintVal); ok {
			return x.UintVal
		}
	}
	return 0
}

func (x *AttributeValue) GetFloatVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_FloatVal); ok {
			return x.FloatVal
		}
	}
	return 0
}

func (x *AttributeValue) GetUuidVal() []byte {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_UuidVal); ok {
			return x.UuidVal
		}
	}
	return nil
}

func (x *AttributeValue) GetDatetimeVal() int64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DatetimeVal); ok {
			return x.DatetimeVal
		}
	}
	return 0
}

func (x *AttributeValue) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

func (x *AttributeValue) GetNullVal() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_NullVal); ok {
			return x.NullVal
		}
	}
	return false
}

func (x *AttributeValue) GetStringArray() *StringArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringArray); ok {
			return x.StringArray
		}
	}
	return nil
}

func (x *AttributeValue) GetIntArray() *IntArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_IntArray); ok {
			return x.IntArray
		}
	}
	return nil
}

func (x *AttributeValue) GetUintArray() *UintArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_UintArray); ok {
			return x.UintArray
		}
	}
	return nil
}

func (x *AttributeValue) GetFloatArray() *FloatArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_FloatArray); ok {
			return x.FloatArray
		}
	}
	return nil
}

func (x *AttributeValue) GetUuidArray() *UuidArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_UuidArray); ok {
			return x.UuidArray
		}
	}
	return nil
}

func (x *AttributeValue) GetDatetimeArray() *DatetimeArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DatetimeArray); ok {
			return x.DatetimeArray
		}
	}
	return nil
}

func (x *AttributeValue) GetBoolArray() *BoolArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BoolArray); ok {
			return x.BoolArray
		}
	}
	return nil
}

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_StringVal struct {
	// Scalar values
	StringVal string `protobuf:"bytes,1,opt,name=string_val,json=stringVal,proto3,oneof"`
}

type AttributeValue_IntVal struct {
	IntVal int64 `protobuf:"varint,2,opt,name=int_val,json=intVal,proto3,oneof"`
}

type AttributeValue_UintVal struct {
	UintVal uint64 `protobuf:"varint,3,opt,name=uint_val,json=uintVal,proto3,oneof"`
}

type AttributeValue_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,4,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type AttributeValue_UuidVal struct {
	UuidVal []byte `protobuf:"bytes,5,opt,name=uuid_val,json=uuidVal,proto3,oneof"` // 16 bytes
}

type AttributeValue_DatetimeVal struct {
	DatetimeVal int64 `protobuf:"varint,6,opt,name=datetime_val,json=datetimeVal,proto3,oneof"` // Unix ms since epoch
}

type AttributeValue_BoolVal struct {
	BoolVal bool `protobuf:"varint,7,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type AttributeValue_NullVal struct {
	// Null value
	NullVal bool `protobuf:"varint,8,opt,name=null_val,json=nullVal,proto3,oneof"`
}

type AttributeValue_StringArray struct {
	// Array values
	StringArray *StringArray `protobuf:"bytes,10,opt,name=string_array,json=stringArray,proto3,oneof"`
}

type AttributeValue_IntArray struct {
	IntArray *IntArray `protobuf:"bytes,11,opt,name=int_array,json=intArray,proto3,oneof"`
}

type AttributeValue_UintArray struct {
	UintArray *UintArray `protobuf:"bytes,12,opt,name=uint_array,json=uintArray,proto3,oneof"`
}

type AttributeValue_FloatArray struct {
	FloatArray *FloatArray `protobuf:"bytes,13,opt,name=float_array,json=floatArray,proto3,oneof"`
}

type AttributeValue_UuidArray struct {
	UuidArray *UuidArray `protobuf:"bytes,14,opt,name=uuid_array,json=uuidArray,proto3,oneof"`
}

type AttributeValue_DatetimeArray struct {
	DatetimeArray *DatetimeArray `protobuf:"bytes,15,opt,name=datetime_array,json=datetimeArray,proto3,oneof"`
}

type AttributeValue_BoolArray struct {
	BoolArray *BoolArray `protobuf:"bytes,16,opt,name=bool_array,json=boolArray,proto3,oneof"`
}

func (*AttributeValue_StringVal) isAttributeValue_Value() {}

func (*AttributeValue_IntVal) isAttributeValue_Value() {}

func (*AttributeValue_UintVal) isAttributeValue_Value() {}

func (*AttributeValue_FloatVal) isAttributeValue_Value() {}

func (*AttributeValue_UuidVal) isAttributeValue_Value() {}

func (*AttributeValue_DatetimeVal) isAttributeValue_Value() {}

func (*AttributeValue_BoolVal) isAttributeValue_Value() {}

func (*AttributeValue_NullVal) isAttributeValue_Value() {}

func (*AttributeValue_StringArray) isAttributeValue_Value() {}

func (*AttributeValue_IntArray) isAttributeValue_Value() {}

func (*AttributeValue_UintArray) isAttributeValue_Value() {}

func (*AttributeValue_FloatArray) isAttributeValue_Value() {}

func (*AttributeValue_UuidArray) isAttributeValue_Value() {}

func (*AttributeValue_DatetimeArray) isAttributeValue_Value() {}

func (*AttributeValue_BoolArray) isAttributeValue_Value() {}

type StringArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	mi := &file_internal_wal_entry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{5}
}

func (x *StringArray) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type IntArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntArray) Reset() {
	*x = IntArray{}
	mi := &file_internal_wal_entry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntArray) ProtoMessage() {}

func (x *IntArray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntArray.ProtoReflect.Descriptor instead.
func (*IntArray) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{6}
}

func (x *IntArray) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type UintArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []uint64               `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UintArray) Reset() {
	*x = UintArray{}
	mi := &file_internal_wal_entry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UintArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UintArray) ProtoMessage() {}

func (x *UintArray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UintArray.ProtoReflect.Descriptor instead.
func (*UintArray) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{7}
}

func (x *UintArray) GetValues() []uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type FloatArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatArray) Reset() {
	*x = FloatArray{}
	mi := &file_internal_wal_entry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatArray) ProtoMessage() {}

func (x *FloatArray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatArray.ProtoReflect.Descriptor instead.
func (*FloatArray) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{8}
}

func (x *FloatArray) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type UuidArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"` // Each element is 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UuidArray) Reset() {
	*x = UuidArray{}
	mi := &file_internal_wal_entry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UuidArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UuidArray) ProtoMessage() {}

func (x *UuidArray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UuidArray.ProtoReflect.Descriptor instead.
func (*UuidArray) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{9}
}

func (x *UuidArray) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type DatetimeArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"` // Unix ms since epoch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatetimeArray) Reset() {
	*x = DatetimeArray{}
	mi := &file_internal_wal_entry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatetimeArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatetimeArray) ProtoMessage() {}

func (x *DatetimeArray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatetimeArray.ProtoReflect.Descriptor instead.
func (*DatetimeArray) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{10}
}

func (x *DatetimeArray) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type BoolArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []bool                 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolArray) Reset() {
	*x = BoolArray{}
	mi := &file_internal_wal_entry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolArray) ProtoMessage() {}

func (x *BoolArray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolArray.ProtoReflect.Descriptor instead.
func (*BoolArray) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{11}
}

func (x *BoolArray) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

// SchemaDelta records a schema change introduced by this batch.
type SchemaDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attribute name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Attribute type
	Type AttributeType `protobuf:"varint,2,opt,name=type,proto3,enum=wal.AttributeType" json:"type,omitempty"`
	// Field options
	Filterable     bool            `protobuf:"varint,3,opt,name=filterable,proto3" json:"filterable,omitempty"`
	Regex          bool            `protobuf:"varint,4,opt,name=regex,proto3" json:"regex,omitempty"`
	FullTextSearch *FullTextConfig `protobuf:"bytes,5,opt,name=full_text_search,json=fullTextSearch,proto3" json:"full_text_search,omitempty"`
	Vector         *VectorConfig   `protobuf:"bytes,6,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchemaDelta) Reset() {
	*x = SchemaDelta{}
	mi := &file_internal_wal_entry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaDelta) ProtoMessage() {}

func (x *SchemaDelta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaDelta.ProtoReflect.Descriptor instead.
func (*SchemaDelta) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{12}
}

func (x *SchemaDelta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaDelta) GetType() AttributeType {
	if x != nil {
		return x.Type
	}
	return AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED
}

func (x *SchemaDelta) GetFilterable() bool {
	if x != nil {
		return x.Filterable
	}
	return false
}

func (x *SchemaDelta) GetRegex() bool {
	if x != nil {
		return x.Regex
	}
	return false
}

func (x *SchemaDelta) GetFullTextSearch() *FullTextConfig {
	if x != nil {
		return x.FullTextSearch
	}
	return nil
}

func (x *SchemaDelta) GetVector() *VectorConfig {
	if x != nil {
		return x.Vector
	}
	return nil
}

type FullTextConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Tokenizer     string                 `protobuf:"bytes,2,opt,name=tokenizer,proto3" json:"tokenizer,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Stemming      bool                   `protobuf:"varint,4,opt,name=stemming,proto3" json:"stemming,omitempty"`
	StopWords     []string               `protobuf:"bytes,5,rep,name=stop_words,json=stopWords,proto3" json:"stop_words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullTextConfig) Reset() {
	*x = FullTextConfig{}
	mi := &file_internal_wal_entry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullTextConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullTextConfig) ProtoMessage() {}

func (x *FullTextConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullTextConfig.ProtoReflect.Descriptor instead.
func (*FullTextConfig) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{13}
}

func (x *FullTextConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FullTextConfig) GetTokenizer() string {
	if x != nil {
		return x.Tokenizer
	}
	return ""
}

func (x *FullTextConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *FullTextConfig) GetStemming() bool {
	if x != nil {
		return x.Stemming
	}
	return false
}

func (x *FullTextConfig) GetStopWords() []string {
	if x != nil {
		return x.StopWords
	}
	return nil
}

type VectorConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Dtype          string                 `protobuf:"bytes,1,opt,name=dtype,proto3" json:"dtype,omitempty"` // "f16" or "f32"
	Dimensions     uint32                 `protobuf:"varint,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	DistanceMetric string                 `protobuf:"bytes,3,opt,name=distance_metric,json=distanceMetric,proto3" json:"distance_metric,omitempty"` // "cosine_distance" or "euclidean_squared"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VectorConfig) Reset() {
	*x = VectorConfig{}
	mi := &file_internal_wal_entry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorConfig) ProtoMessage() {}

func (x *VectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorConfig.ProtoReflect.Descriptor instead.
func (*VectorConfig) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{14}
}

func (x *VectorConfig) GetDtype() string {
	if x != nil {
		return x.Dtype
	}
	return ""
}

func (x *VectorConfig) GetDimensions() uint32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *VectorConfig) GetDistanceMetric() string {
	if x != nil {
		return x.DistanceMetric
	}
	return ""
}

// SubBatchStats records statistics about the sub-batch.
type SubBatchStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowsAffected  int64                  `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	RowsUpserted  int64                  `protobuf:"varint,2,opt,name=rows_upserted,json=rowsUpserted,proto3" json:"rows_upserted,omitempty"`
	RowsPatched   int64                  `protobuf:"varint,3,opt,name=rows_patched,json=rowsPatched,proto3" json:"rows_patched,omitempty"`
	RowsDeleted   int64                  `protobuf:"varint,4,opt,name=rows_deleted,json=rowsDeleted,proto3" json:"rows_deleted,omitempty"`
	RowsRemaining bool                   `protobuf:"varint,5,opt,name=rows_remaining,json=rowsRemaining,proto3" json:"rows_remaining,omitempty"` // True if filter-based write hit cap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubBatchStats) Reset() {
	*x = SubBatchStats{}
	mi := &file_internal_wal_entry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubBatchStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubBatchStats) ProtoMessage() {}

func (x *SubBatchStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubBatchStats.ProtoReflect.Descriptor instead.
func (*SubBatchStats) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{15}
}

func (x *SubBatchStats) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *SubBatchStats) GetRowsUpserted() int64 {
	if x != nil {
		return x.RowsUpserted
	}
	return 0
}

func (x *SubBatchStats) GetRowsPatched() int64 {
	if x != nil {
		return x.RowsPatched
	}
	return 0
}

func (x *SubBatchStats) GetRowsDeleted() int64 {
	if x != nil {
		return x.RowsDeleted
	}
	return 0
}

func (x *SubBatchStats) GetRowsRemaining() bool {
	if x != nil {
		return x.RowsRemaining
	}
	return false
}

// FilterOperation records details about filter-based operations.
type FilterOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  FilterOperationType    `protobuf:"varint,1,opt,name=type,proto3,enum=wal.FilterOperationType" json:"type,omitempty"`
	// The WAL seq at which phase 1 was evaluated
	Phase1SnapshotSeq uint64 `protobuf:"varint,2,opt,name=phase1_snapshot_seq,json=phase1SnapshotSeq,proto3" json:"phase1_snapshot_seq,omitempty"`
	// The IDs selected in phase 1 (bounded by limits)
	CandidateIds []*DocumentID `protobuf:"bytes,3,rep,name=candidate_ids,json=candidateIds,proto3" json:"candidate_ids,omitempty"`
	// The original filter expression (JSON-encoded)
	FilterJson string `protobuf:"bytes,4,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"`
	// The patch payload for patch_by_filter (JSON-encoded)
	PatchJson string `protobuf:"bytes,5,opt,name=patch_json,json=patchJson,proto3" json:"patch_json,omitempty"`
	// Whether partial application is allowed
	AllowPartial  bool `protobuf:"varint,6,opt,name=allow_partial,json=allowPartial,proto3" json:"allow_partial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterOperation) Reset() {
	*x = FilterOperation{}
	mi := &file_internal_wal_entry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOperation) ProtoMessage() {}

func (x *FilterOperation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wal_entry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOperation.ProtoReflect.Descriptor instead.
func (*FilterOperation) Descriptor() ([]byte, []int) {
	return file_internal_wal_entry_proto_rawDescGZIP(), []int{16}
}

func (x *FilterOperation) GetType() FilterOperationType {
	if x != nil {
		return x.Type
	}
	return FilterOperationType_FILTER_OPERATION_TYPE_UNSPECIFIED
}

func (x *FilterOperation) GetPhase1SnapshotSeq() uint64 {
	if x != nil {
		return x.Phase1SnapshotSeq
	}
	return 0
}

func (x *FilterOperation) GetCandidateIds() []*DocumentID {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

func (x *FilterOperation) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

func (x *FilterOperation) GetPatchJson() string {
	if x != nil {
		return x.PatchJson
	}
	return ""
}

func (x *FilterOperation) GetAllowPartial() bool {
	if x != nil {
		return x.AllowPartial
	}
	return false
}

var File_internal_wal_entry_proto protoreflect.FileDescriptor

const file_internal_wal_entry_proto_rawDesc = "" +
	"\n" +
	"\x18internal/wal/entry.proto\x12\x03wal\"\xde\x01\n" +
	"\bWalEntry\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12*\n" +
	"\x11committed_unix_ms\x18\x04 \x01(\x03R\x0fcommittedUnixMs\x123\n" +
	"\vsub_batches\x18\x05 \x03(\v2\x12.wal.WriteSubBatchR\n" +
	"subBatches\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\fR\bchecksum\"\x95\x02\n" +
	"\rWriteSubBatch\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12$\n" +
	"\x0ereceived_at_ms\x18\x02 \x01(\x03R\freceivedAtMs\x12+\n" +
	"\tmutations\x18\x03 \x03(\v2\r.wal.MutationR\tmutations\x12(\n" +
	"\x05stats\x18\x04 \x01(\v2\x12.wal.SubBatchStatsR\x05stats\x125\n" +
	"\rschema_deltas\x18\x05 \x03(\v2\x10.wal.SchemaDeltaR\fschemaDeltas\x121\n" +
	"\tfilter_op\x18\x06 \x01(\v2\x14.wal.FilterOperationR\bfilterOp\"\xe5\x02\n" +
	"\bMutation\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.wal.MutationTypeR\x04type\x12\x1f\n" +
	"\x02id\x18\x02 \x01(\v2\x0f.wal.DocumentIDR\x02id\x12=\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x1d.wal.Mutation.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06vector\x18\x04 \x01(\fR\x06vector\x12\x1f\n" +
	"\vvector_dims\x18\x05 \x01(\rR\n" +
	"vectorDims\x12 \n" +
	"\vconditional\x18\x06 \x01(\bR\vconditional\x12#\n" +
	"\rcondition_met\x18\a \x01(\bR\fconditionMet\x1aR\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.wal.AttributeValueR\x05value:\x028\x01\"P\n" +
	"\n" +
	"DocumentID\x12\x12\n" +
	"\x03u64\x18\x01 \x01(\x04H\x00R\x03u64\x12\x14\n" +
	"\x04uuid\x18\x02 \x01(\fH\x00R\x04uuid\x12\x12\n" +
	"\x03str\x18\x03 \x01(\tH\x00R\x03strB\x04\n" +
	"\x02id\"\xf6\x04\n" +
	"\x0eAttributeValue\x12\x1f\n" +
	"\n" +
	"string_val\x18\x01 \x01(\tH\x00R\tstringVal\x12\x19\n" +
	"\aint_val\x18\x02 \x01(\x03H\x00R\x06intVal\x12\x1b\n" +
	"\buint_val\x18\x03 \x01(\x04H\x00R\auintVal\x12\x1d\n" +
	"\tfloat_val\x18\x04 \x01(\x01H\x00R\bfloatVal\x12\x1b\n" +
	"\buuid_val\x18\x05 \x01(\fH\x00R\auuidVal\x12#\n" +
	"\fdatetime_val\x18\x06 \x01(\x03H\x00R\vdatetimeVal\x12\x1b\n" +
	"\bbool_val\x18\a \x01(\bH\x00R\aboolVal\x12\x1b\n" +
	"\bnull_val\x18\b \x01(\bH\x00R\anullVal\x125\n" +
	"\fstring_array\x18\n" +
	" \x01(\v2\x10.wal.StringArrayH\x00R\vstringArray\x12,\n" +
	"\tint_array\x18\v \x01(\v2\r.wal.IntArrayH\x00R\bintArray\x12/\n" +
	"\n" +
	"uint_array\x18\f \x01(\v2\x0e.wal.UintArrayH\x00R\tuintArray\x122\n" +
	"\vfloat_array\x18\r \x01(\v2\x0f.wal.FloatArrayH\x00R\n" +
	"floatArray\x12/\n" +
	"\n" +
	"uuid_array\x18\x0e \x01(\v2\x0e.wal.UuidArrayH\x00R\tuuidArray\x12;\n" +
	"\x0edatetime_array\x18\x0f \x01(\v2\x12.wal.DatetimeArrayH\x00R\rdatetimeArray\x12/\n" +
	"\n" +
	"bool_array\x18\x10 \x01(\v2\x0e.wal.BoolArrayH\x00R\tboolArrayB\a\n" +
	"\x05value\"%\n" +
	"\vStringArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\"\n" +
	"\bIntArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\"#\n" +
	"\tUintArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x04R\x06values\"$\n" +
	"\n" +
	"FloatArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"#\n" +
	"\tUuidArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"'\n" +
	"\rDatetimeArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06values\"#\n" +
	"\tBoolArray\x12\x16\n" +
	"\x06values\x18\x01 \x03(\bR\x06values\"\xe9\x01\n" +
	"\vSchemaDelta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.wal.AttributeTypeR\x04type\x12\x1e\n" +
	"\n" +
	"filterable\x18\x03 \x01(\bR\n" +
	"filterable\x12\x14\n" +
	"\x05regex\x18\x04 \x01(\bR\x05regex\x12=\n" +
	"\x10full_text_search\x18\x05 \x01(\v2\x13.wal.FullTextConfigR\x0efullTextSearch\x12)\n" +
	"\x06vector\x18\x06 \x01(\v2\x11.wal.VectorConfigR\x06vector\"\x9f\x01\n" +
	"\x0eFullTextConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1c\n" +
	"\ttokenizer\x18\x02 \x01(\tR\ttokenizer\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1a\n" +
	"\bstemming\x18\x04 \x01(\bR\bstemming\x12\x1d\n" +
	"\n" +
	"stop_words\x18\x05 \x03(\tR\tstopWords\"m\n" +
	"\fVectorConfig\x12\x14\n" +
	"\x05dtype\x18\x01 \x01(\tR\x05dtype\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x01(\rR\n" +
	"dimensions\x12'\n" +
	"\x0fdistance_metric\x18\x03 \x01(\tR\x0edistanceMetric\"\xc6\x01\n" +
	"\rSubBatchStats\x12#\n" +
	"\rrows_affected\x18\x01 \x01(\x03R\frowsAffected\x12#\n" +
	"\rrows_upserted\x18\x02 \x01(\x03R\frowsUpserted\x12!\n" +
	"\frows_patched\x18\x03 \x01(\x03R\vrowsPatched\x12!\n" +
	"\frows_deleted\x18\x04 \x01(\x03R\vrowsDeleted\x12%\n" +
	"\x0erows_remaining\x18\x05 \x01(\bR\rrowsRemaining\"\x8a\x02\n" +
	"\x0fFilterOperation\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.wal.FilterOperationTypeR\x04type\x12.\n" +
	"\x13phase1_snapshot_seq\x18\x02 \x01(\x04R\x11phase1SnapshotSeq\x124\n" +
	"\rcandidate_ids\x18\x03 \x03(\v2\x0f.wal.DocumentIDR\fcandidateIds\x12\x1f\n" +
	"\vfilter_json\x18\x04 \x01(\tR\n" +
	"filterJson\x12\x1d\n" +
	"\n" +
	"patch_json\x18\x05 \x01(\tR\tpatchJson\x12#\n" +
	"\rallow_partial\x18\x06 \x01(\bR\fallowPartial*z\n" +
	"\fMutationType\x12\x1d\n" +
	"\x19MUTATION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MUTATION_TYPE_UPSERT\x10\x01\x12\x17\n" +
	"\x13MUTATION_TYPE_PATCH\x10\x02\x12\x18\n" +
	"\x14MUTATION_TYPE_DELETE\x10\x03*\xc3\x03\n" +
	"\rAttributeType\x12\x1e\n" +
	"\x1aATTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ATTRIBUTE_TYPE_STRING\x10\x01\x12\x16\n" +
	"\x12ATTRIBUTE_TYPE_INT\x10\x02\x12\x17\n" +
	"\x13ATTRIBUTE_TYPE_UINT\x10\x03\x12\x18\n" +
	"\x14ATTRIBUTE_TYPE_FLOAT\x10\x04\x12\x17\n" +
	"\x13ATTRIBUTE_TYPE_UUID\x10\x05\x12\x1b\n" +
	"\x17ATTRIBUTE_TYPE_DATETIME\x10\x06\x12\x17\n" +
	"\x13ATTRIBUTE_TYPE_BOOL\x10\a\x12\x1f\n" +
	"\x1bATTRIBUTE_TYPE_STRING_ARRAY\x10\v\x12\x1c\n" +
	"\x18ATTRIBUTE_TYPE_INT_ARRAY\x10\f\x12\x1d\n" +
	"\x19ATTRIBUTE_TYPE_UINT_ARRAY\x10\r\x12\x1e\n" +
	"\x1aATTRIBUTE_TYPE_FLOAT_ARRAY\x10\x0e\x12\x1d\n" +
	"\x19ATTRIBUTE_TYPE_UUID_ARRAY\x10\x0f\x12!\n" +
	"\x1dATTRIBUTE_TYPE_DATETIME_ARRAY\x10\x10\x12\x1d\n" +
	"\x19ATTRIBUTE_TYPE_BOOL_ARRAY\x10\x11*\x7f\n" +
	"\x13FilterOperationType\x12%\n" +
	"!FILTER_OPERATION_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cFILTER_OPERATION_TYPE_DELETE\x10\x01\x12\x1f\n" +
	"\x1bFILTER_OPERATION_TYPE_PATCH\x10\x02B'Z%github.com/vexsearch/vex/internal/walb\x06proto3"

var (
	file_internal_wal_entry_proto_rawDescOnce sync.Once
	file_internal_wal_entry_proto_rawDescData []byte
)

func file_internal_wal_entry_proto_rawDescGZIP() []byte {
	file_internal_wal_entry_proto_rawDescOnce.Do(func() {
		file_internal_wal_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_wal_entry_proto_rawDesc), len(file_internal_wal_entry_proto_rawDesc)))
	})
	return file_internal_wal_entry_proto_rawDescData
}

var file_internal_wal_entry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_wal_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_wal_entry_proto_goTypes = []any{
	(MutationType)(0),        // 0: wal.MutationType
	(AttributeType)(0),       // 1: wal.AttributeType
	(FilterOperationType)(0), // 2: wal.FilterOperationType
	(*WalEntry)(nil),         // 3: wal.WalEntry
	(*WriteSubBatch)(nil),    // 4: wal.WriteSubBatch
	(*Mutation)(nil),         // 5: wal.Mutation
	(*DocumentID)(nil),       // 6: wal.DocumentID
	(*AttributeValue)(nil),   // 7: wal.AttributeValue
	(*StringArray)(nil),      // 8: wal.StringArray
	(*IntArray)(nil),         // 9: wal.IntArray
	(*UintArray)(nil),        // 10: wal.UintArray
	(*FloatArray)(nil),       // 11: wal.FloatArray
	(*UuidArray)(nil),        // 12: wal.UuidArray
	(*DatetimeArray)(nil),    // 13: wal.DatetimeArray
	(*BoolArray)(nil),        // 14: wal.BoolArray
	(*SchemaDelta)(nil),      // 15: wal.SchemaDelta
	(*FullTextConfig)(nil),   // 16: wal.FullTextConfig
	(*VectorConfig)(nil),     // 17: wal.VectorConfig
	(*SubBatchStats)(nil),    // 18: wal.SubBatchStats
	(*FilterOperation)(nil),  // 19: wal.FilterOperation
	nil,                      // 20: wal.Mutation.AttributesEntry
}
var file_internal_wal_entry_proto_depIdxs = []int32{
	4,  // 0: wal.WalEntry.sub_batches:type_name -> wal.WriteSubBatch
	5,  // 1: wal.WriteSubBatch.mutations:type_name -> wal.Mutation
	18, // 2: wal.WriteSubBatch.stats:type_name -> wal.SubBatchStats
	15, // 3: wal.WriteSubBatch.schema_deltas:type_name -> wal.SchemaDelta
	19, // 4: wal.WriteSubBatch.filter_op:type_name -> wal.FilterOperation
	0,  // 5: wal.Mutation.type:type_name -> wal.MutationType
	6,  // 6: wal.Mutation.id:type_name -> wal.DocumentID
	20, // 7: wal.Mutation.attributes:type_name -> wal.Mutation.AttributesEntry
	8,  // 8: wal.AttributeValue.string_array:type_name -> wal.StringArray
	9,  // 9: wal.AttributeValue.int_array:type_name -> wal.IntArray
	10, // 10: wal.AttributeValue.uint_array:type_name -> wal.UintArray
	11, // 11: wal.AttributeValue.float_array:type_name -> wal.FloatArray
	12, // 12: wal.AttributeValue.uuid_array:type_name -> wal.UuidArray
	13, // 13: wal.AttributeValue.datetime_array:type_name -> wal.DatetimeArray
	14, // 14: wal.AttributeValue.bool_array:type_name -> wal.BoolArray
	1,  // 15: wal.SchemaDelta.type:type_name -> wal.AttributeType
	16, // 16: wal.SchemaDelta.full_text_search:type_name -> wal.FullTextConfig
	17, // 17: wal.SchemaDelta.vector:type_name -> wal.VectorConfig
	2,  // 18: wal.FilterOperation.type:type_name -> wal.FilterOperationType
	6,  // 19: wal.FilterOperation.candidate_ids:type_name -> wal.DocumentID
	7,  // 20: wal.Mutation.AttributesEntry.value:type_name -> wal.AttributeValue
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_wal_entry_proto_init() }
func file_internal_wal_entry_proto_init() {
	if File_internal_wal_entry_proto != nil {
		return
	}
	file_internal_wal_entry_proto_msgTypes[3].OneofWrappers = []any{
		(*DocumentID_U64)(nil),
		(*DocumentID_Uuid)(nil),
		(*DocumentID_Str)(nil),
	}
	file_internal_wal_entry_proto_msgTypes[4].OneofWrappers = []any{
		(*AttributeValue_StringVal)(nil),
		(*AttributeValue_IntVal)(nil),
		(*AttributeValue_UintVal)(nil),
		(*AttributeValue_FloatVal)(nil),
		(*AttributeValue_UuidVal)(nil),
		(*AttributeValue_DatetimeVal)(nil),
		(*AttributeValue_BoolVal)(nil),
		(*AttributeValue_NullVal)(nil),
		(*AttributeValue_StringArray)(nil),
		(*AttributeValue_IntArray)(nil),
		(*AttributeValue_UintArray)(nil),
		(*AttributeValue_FloatArray)(nil),
		(*AttributeValue_UuidArray)(nil),
		(*AttributeValue_DatetimeArray)(nil),
		(*AttributeValue_BoolArray)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_wal_entry_proto_rawDesc), len(file_internal_wal_entry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_wal_entry_proto_goTypes,
		DependencyIndexes: file_internal_wal_entry_proto_depIdxs,
		EnumInfos:         file_internal_wal_entry_proto_enumTypes,
		MessageInfos:      file_internal_wal_entry_proto_msgTypes,
	}.Build()
	File_internal_wal_entry_proto = out.File
	file_internal_wal_entry_proto_goTypes = nil
	file_internal_wal_entry_proto_depIdxs = nil
}
